//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.04 at 02:01:38 PM CEST 
//


package de.w3l.anw.wetterstation.xml.adaten;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="termsofService" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="features">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="feature" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="moon_phase">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="percentIlluminated" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="ageOfMoon" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="current_time">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="sunset">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="sunrise">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sun_phase">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="sunset">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="sunrise">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "version",
    "termsofService",
    "features",
    "moonPhase",
    "sunPhase"
})
@XmlRootElement(name = "response")
public class Astronomie {

    protected float version;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String termsofService;
    @XmlElement(required = true)
    protected Astronomie.Features features;
    @XmlElement(name = "moon_phase", required = true)
    protected Astronomie.MoonPhase moonPhase;
    @XmlElement(name = "sun_phase", required = true)
    protected Astronomie.SunPhase sunPhase;

    /**
     * Gets the value of the version property.
     * 
     */
    public float getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     */
    public void setVersion(float value) {
        this.version = value;
    }

    /**
     * Gets the value of the termsofService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermsofService() {
        return termsofService;
    }

    /**
     * Sets the value of the termsofService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermsofService(String value) {
        this.termsofService = value;
    }

    /**
     * Gets the value of the features property.
     * 
     * @return
     *     possible object is
     *     {@link Astronomie.Features }
     *     
     */
    public Astronomie.Features getFeatures() {
        return features;
    }

    /**
     * Sets the value of the features property.
     * 
     * @param value
     *     allowed object is
     *     {@link Astronomie.Features }
     *     
     */
    public void setFeatures(Astronomie.Features value) {
        this.features = value;
    }

    /**
     * Gets the value of the moonPhase property.
     * 
     * @return
     *     possible object is
     *     {@link Astronomie.MoonPhase }
     *     
     */
    public Astronomie.MoonPhase getMoonPhase() {
        return moonPhase;
    }

    /**
     * Sets the value of the moonPhase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Astronomie.MoonPhase }
     *     
     */
    public void setMoonPhase(Astronomie.MoonPhase value) {
        this.moonPhase = value;
    }

    /**
     * Gets the value of the sunPhase property.
     * 
     * @return
     *     possible object is
     *     {@link Astronomie.SunPhase }
     *     
     */
    public Astronomie.SunPhase getSunPhase() {
        return sunPhase;
    }

    /**
     * Sets the value of the sunPhase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Astronomie.SunPhase }
     *     
     */
    public void setSunPhase(Astronomie.SunPhase value) {
        this.sunPhase = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="feature" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "feature"
    })
    public static class Features {

        @XmlElement(required = true)
        protected String feature;

        /**
         * Gets the value of the feature property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFeature() {
            return feature;
        }

        /**
         * Sets the value of the feature property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFeature(String value) {
            this.feature = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="percentIlluminated" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="ageOfMoon" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="current_time">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="sunset">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="sunrise">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "percentIlluminated",
        "ageOfMoon",
        "currentTime",
        "sunset",
        "sunrise"
    })
    public static class MoonPhase {

        protected byte percentIlluminated;
        protected byte ageOfMoon;
        @XmlElement(name = "current_time", required = true)
        protected Astronomie.MoonPhase.CurrentTime currentTime;
        @XmlElement(required = true)
        protected Astronomie.MoonPhase.Sunset sunset;
        @XmlElement(required = true)
        protected Astronomie.MoonPhase.Sunrise sunrise;

        /**
         * Gets the value of the percentIlluminated property.
         * 
         */
        public byte getPercentIlluminated() {
            return percentIlluminated;
        }

        /**
         * Sets the value of the percentIlluminated property.
         * 
         */
        public void setPercentIlluminated(byte value) {
            this.percentIlluminated = value;
        }

        /**
         * Gets the value of the ageOfMoon property.
         * 
         */
        public byte getAgeOfMoon() {
            return ageOfMoon;
        }

        /**
         * Sets the value of the ageOfMoon property.
         * 
         */
        public void setAgeOfMoon(byte value) {
            this.ageOfMoon = value;
        }

        /**
         * Gets the value of the currentTime property.
         * 
         * @return
         *     possible object is
         *     {@link Astronomie.MoonPhase.CurrentTime }
         *     
         */
        public Astronomie.MoonPhase.CurrentTime getCurrentTime() {
            return currentTime;
        }

        /**
         * Sets the value of the currentTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Astronomie.MoonPhase.CurrentTime }
         *     
         */
        public void setCurrentTime(Astronomie.MoonPhase.CurrentTime value) {
            this.currentTime = value;
        }

        /**
         * Gets the value of the sunset property.
         * 
         * @return
         *     possible object is
         *     {@link Astronomie.MoonPhase.Sunset }
         *     
         */
        public Astronomie.MoonPhase.Sunset getSunset() {
            return sunset;
        }

        /**
         * Sets the value of the sunset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Astronomie.MoonPhase.Sunset }
         *     
         */
        public void setSunset(Astronomie.MoonPhase.Sunset value) {
            this.sunset = value;
        }

        /**
         * Gets the value of the sunrise property.
         * 
         * @return
         *     possible object is
         *     {@link Astronomie.MoonPhase.Sunrise }
         *     
         */
        public Astronomie.MoonPhase.Sunrise getSunrise() {
            return sunrise;
        }

        /**
         * Sets the value of the sunrise property.
         * 
         * @param value
         *     allowed object is
         *     {@link Astronomie.MoonPhase.Sunrise }
         *     
         */
        public void setSunrise(Astronomie.MoonPhase.Sunrise value) {
            this.sunrise = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hour",
            "minute"
        })
        public static class CurrentTime {

            protected byte hour;
            protected byte minute;

            /**
             * Gets the value of the hour property.
             * 
             */
            public byte getHour() {
                return hour;
            }

            /**
             * Sets the value of the hour property.
             * 
             */
            public void setHour(byte value) {
                this.hour = value;
            }

            /**
             * Gets the value of the minute property.
             * 
             */
            public byte getMinute() {
                return minute;
            }

            /**
             * Sets the value of the minute property.
             * 
             */
            public void setMinute(byte value) {
                this.minute = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hour",
            "minute"
        })
        public static class Sunrise {

            protected byte hour;
            protected byte minute;

            /**
             * Gets the value of the hour property.
             * 
             */
            public byte getHour() {
                return hour;
            }

            /**
             * Sets the value of the hour property.
             * 
             */
            public void setHour(byte value) {
                this.hour = value;
            }

            /**
             * Gets the value of the minute property.
             * 
             */
            public byte getMinute() {
                return minute;
            }

            /**
             * Sets the value of the minute property.
             * 
             */
            public void setMinute(byte value) {
                this.minute = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hour",
            "minute"
        })
        public static class Sunset {

            protected byte hour;
            protected byte minute;

            /**
             * Gets the value of the hour property.
             * 
             */
            public byte getHour() {
                return hour;
            }

            /**
             * Sets the value of the hour property.
             * 
             */
            public void setHour(byte value) {
                this.hour = value;
            }

            /**
             * Gets the value of the minute property.
             * 
             */
            public byte getMinute() {
                return minute;
            }

            /**
             * Sets the value of the minute property.
             * 
             */
            public void setMinute(byte value) {
                this.minute = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="sunset">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="sunrise">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sunset",
        "sunrise"
    })
    public static class SunPhase {

        @XmlElement(required = true)
        protected Astronomie.SunPhase.Sunset sunset;
        @XmlElement(required = true)
        protected Astronomie.SunPhase.Sunrise sunrise;

        /**
         * Gets the value of the sunset property.
         * 
         * @return
         *     possible object is
         *     {@link Astronomie.SunPhase.Sunset }
         *     
         */
        public Astronomie.SunPhase.Sunset getSunset() {
            return sunset;
        }

        /**
         * Sets the value of the sunset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Astronomie.SunPhase.Sunset }
         *     
         */
        public void setSunset(Astronomie.SunPhase.Sunset value) {
            this.sunset = value;
        }

        /**
         * Gets the value of the sunrise property.
         * 
         * @return
         *     possible object is
         *     {@link Astronomie.SunPhase.Sunrise }
         *     
         */
        public Astronomie.SunPhase.Sunrise getSunrise() {
            return sunrise;
        }

        /**
         * Sets the value of the sunrise property.
         * 
         * @param value
         *     allowed object is
         *     {@link Astronomie.SunPhase.Sunrise }
         *     
         */
        public void setSunrise(Astronomie.SunPhase.Sunrise value) {
            this.sunrise = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hour",
            "minute"
        })
        public static class Sunrise {

            protected byte hour;
            protected byte minute;

            /**
             * Gets the value of the hour property.
             * 
             */
            public byte getHour() {
                return hour;
            }

            /**
             * Sets the value of the hour property.
             * 
             */
            public void setHour(byte value) {
                this.hour = value;
            }

            /**
             * Gets the value of the minute property.
             * 
             */
            public byte getMinute() {
                return minute;
            }

            /**
             * Sets the value of the minute property.
             * 
             */
            public void setMinute(byte value) {
                this.minute = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hour",
            "minute"
        })
        public static class Sunset {

            protected byte hour;
            protected byte minute;

            /**
             * Gets the value of the hour property.
             * 
             */
            public byte getHour() {
                return hour;
            }

            /**
             * Sets the value of the hour property.
             * 
             */
            public void setHour(byte value) {
                this.hour = value;
            }

            /**
             * Gets the value of the minute property.
             * 
             */
            public byte getMinute() {
                return minute;
            }

            /**
             * Sets the value of the minute property.
             * 
             */
            public void setMinute(byte value) {
                this.minute = value;
            }

        }

    }

}
