//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.04 at 02:01:38 PM CEST 
//


package de.w3l.anw.wetterstation.xml.adaten;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.w3l.anw.wetterstation.xml.adaten package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.w3l.anw.wetterstation.xml.adaten
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Astronomie }
     * 
     */
    public Astronomie createResponse() {
        return new Astronomie();
    }

    /**
     * Create an instance of {@link Astronomie.SunPhase }
     * 
     */
    public Astronomie.SunPhase createResponseSunPhase() {
        return new Astronomie.SunPhase();
    }

    /**
     * Create an instance of {@link Astronomie.MoonPhase }
     * 
     */
    public Astronomie.MoonPhase createResponseMoonPhase() {
        return new Astronomie.MoonPhase();
    }

    /**
     * Create an instance of {@link Astronomie.Features }
     * 
     */
    public Astronomie.Features createResponseFeatures() {
        return new Astronomie.Features();
    }

    /**
     * Create an instance of {@link Astronomie.SunPhase.Sunset }
     * 
     */
    public Astronomie.SunPhase.Sunset createResponseSunPhaseSunset() {
        return new Astronomie.SunPhase.Sunset();
    }

    /**
     * Create an instance of {@link Astronomie.SunPhase.Sunrise }
     * 
     */
    public Astronomie.SunPhase.Sunrise createResponseSunPhaseSunrise() {
        return new Astronomie.SunPhase.Sunrise();
    }

    /**
     * Create an instance of {@link Astronomie.MoonPhase.CurrentTime }
     * 
     */
    public Astronomie.MoonPhase.CurrentTime createResponseMoonPhaseCurrentTime() {
        return new Astronomie.MoonPhase.CurrentTime();
    }

    /**
     * Create an instance of {@link Astronomie.MoonPhase.Sunset }
     * 
     */
    public Astronomie.MoonPhase.Sunset createResponseMoonPhaseSunset() {
        return new Astronomie.MoonPhase.Sunset();
    }

    /**
     * Create an instance of {@link Astronomie.MoonPhase.Sunrise }
     * 
     */
    public Astronomie.MoonPhase.Sunrise createResponseMoonPhaseSunrise() {
        return new Astronomie.MoonPhase.Sunrise();
    }

}
